// Generated by watcher catalog --typescript. Do not edit.
export const ENGINE_VERSION = "0.1.0+0cab16469056a3ec" as const;

export type AddInput = {
"file": string;
"watch": {
"actions": Array<{
"command"?: Array<string>;
"description": string;
"kind": "record" | "notify" | "command";
"name": string;
"repeat_every_seconds"?: number;
}>;
"cadence"?: {
"every_seconds"?: number;
"quiet_seconds"?: number;
};
"confirm"?: string;
"criteria": Array<{
"id": string;
"text": string;
}>;
"enabled"?: boolean;
"escalate"?: string;
"generation"?: number;
"labels"?: {
[key: string]: string;
};
"max_cost_usd"?: number;
"name": string;
"oneshot"?: boolean;
"preset"?: string;
"source": {
"command"?: Array<string>;
"from_start"?: boolean;
"path"?: string;
"start_inode"?: number;
"start_position"?: number;
"type": "file" | "command" | "stdin";
};
"window_max_chars"?: number;
};
};
export type AddResult = {
"ok": boolean;
};

export type RemoveInput = {
"name": string;
};
export type RemoveResult = {
"ok": boolean;
};

export type ApplyInput = {
"file": string;
"watches": Array<{
"actions": Array<{
"command"?: Array<string>;
"description": string;
"kind": "record" | "notify" | "command";
"name": string;
"repeat_every_seconds"?: number;
}>;
"cadence"?: {
"every_seconds"?: number;
"quiet_seconds"?: number;
};
"confirm"?: string;
"criteria": Array<{
"id": string;
"text": string;
}>;
"enabled"?: boolean;
"escalate"?: string;
"generation"?: number;
"labels"?: {
[key: string]: string;
};
"max_cost_usd"?: number;
"name": string;
"oneshot"?: boolean;
"preset"?: string;
"source": {
"command"?: Array<string>;
"from_start"?: boolean;
"path"?: string;
"start_inode"?: number;
"start_position"?: number;
"type": "file" | "command" | "stdin";
};
"window_max_chars"?: number;
}>;
};
export type ApplyResult = {
"ok": boolean;
};

export type EnableInput = {
"name": string;
};
export type EnableResult = {
"ok": boolean;
};

export type DisableInput = {
"name": string;
};
export type DisableResult = {
"ok": boolean;
};

export type StatusInput = {

};
export type StatusResult = {
"daemon_alive": boolean;
"pending_alerts": number;
"pid": number;
"watches": Array<{
"enabled": boolean;
"generation": (number | null);
"heartbeat": number;
"last_error"?: string;
"loaded_generation": (number | null);
"name": string;
"spent_usd": number;
"state": string;
"terminal_reason"?: string;
}>;
};

export type FindingsInput = {
"labels"?: Array<string>;
"since"?: number;
"watch"?: string;
};
export type FindingsResult = Array<{
"action": string;
"criterion": string;
"evidence": string;
"generation": (number | null);
"id": string;
"labels": {
[key: string]: string;
};
"observed_at": number;
"seq": number;
"status": "ok" | "rejected";
"summary": string;
"watch": string;
}>;

export type AlertsInput = {

};
export type AlertsResult = Array<{
"attempts": number;
"created_at": number;
"delivered_at": (number | null);
"evidence": string;
"id": string;
"last_error": string;
"next_at": number;
"repeat_seconds": number;
"summary": string;
"watch": string;
}>;

export type AckInput = {
"id"?: string;
"watch"?: string;
};
export type AckResult = {
"acknowledged": Array<string>;
};

export type WakeInput = {
"name"?: string;
};
export type WakeResult = {
"ok": boolean;
};

export type JudgeInput = {
"criteria": Array<string>;
"name"?: string;
"preset"?: string;
};
export type JudgeResult = {
"budget_exhausted": boolean;
"calls": Array<{
"cost_usd": (number | null);
"error"?: string;
"model": string;
"phase": string;
"request_id": string;
"service_tier": string;
"usage": {
"input_tokens": number;
"input_tokens_details": {
"cached_tokens": number;
};
"output_tokens": number;
};
}>;
"cost_usd": (number | null);
"findings": Array<{
"action": string;
"call_id"?: string;
"criterion": string;
"evidence": string;
"status": "ok" | "rejected";
"summary": string;
}>;
};

export type PresetsInput = {

};
export type PresetsResult = {
[key: string]: {
"api_key_env": string;
"base_url"?: string;
"cadence": {
"every_seconds"?: number;
"quiet_seconds"?: number;
};
"model": string;
"price_cached_input_per_mtok": (number | null);
"price_input_per_mtok": (number | null);
"price_output_per_mtok": (number | null);
"reasoning_effort"?: string;
"service_tier"?: string;
"window_max_chars": number;
};
};

export type WatchInput = {
"cmd"?: string;
"criteria": Array<string>;
"every"?: number;
"file"?: string;
"from_start"?: boolean;
"max_cost"?: number;
"name"?: string;
"notify"?: boolean;
"oneshot"?: boolean;
"preset"?: string;
"quiet"?: number;
"stdin"?: boolean;
"window"?: number;
};
export type WatchResult = {
"action": string;
"criterion": string;
"evidence": string;
"generation": (number | null);
"id": string;
"labels": {
[key: string]: string;
};
"observed_at": number;
"seq": number;
"status": "ok" | "rejected";
"summary": string;
"watch": string;
};

export type DaemonInput = {

};
export type DaemonResult = {
"ok": boolean;
};

export type ServiceInput = {
"action": "install" | "uninstall" | "status";
"env_file"?: string;
};
export type ServiceResult = {
"status": string;
};

export type CheckInput = {

};
export type CheckResult = {
"enabled": number;
"ok": boolean;
"watches": number;
};

export type CatalogResult = {
"commands": Array<{
"description": string;
"inputSchema": {
[key: string]: unknown;
};
"name": string;
"resultSchema": {
[key: string]: unknown;
};
}>;
"operators": Array<{
"description": string;
"inputSchema": {
[key: string]: unknown;
};
"name": string;
"resultSchema": {
[key: string]: unknown;
};
}>;
"version": string;
};

export interface Commands {
"add": { input: AddInput; result: AddResult };
"remove": { input: RemoveInput; result: RemoveResult };
"apply": { input: ApplyInput; result: ApplyResult };
"enable": { input: EnableInput; result: EnableResult };
"disable": { input: DisableInput; result: DisableResult };
"status": { input: StatusInput; result: StatusResult };
"findings": { input: FindingsInput; result: FindingsResult };
"alerts": { input: AlertsInput; result: AlertsResult };
"ack": { input: AckInput; result: AckResult };
"wake": { input: WakeInput; result: WakeResult };
"judge": { input: JudgeInput; result: JudgeResult };
"presets": { input: PresetsInput; result: PresetsResult };
"catalog": { input: Record<string, never>; result: CatalogResult };
}
export type Command = keyof Commands;

// Operator commands use their CLI lifecycle; watch emits a stream of WatchResult rows.
export interface OperatorCommands {
"watch": { input: WatchInput; result: WatchResult };
"daemon": { input: DaemonInput; result: DaemonResult };
"service": { input: ServiceInput; result: ServiceResult };
"check": { input: CheckInput; result: CheckResult };
}
