package cli

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/markschroedr/watcher-core/internal/config"
	"github.com/markschroedr/watcher-core/internal/delivery"
	"github.com/markschroedr/watcher-core/internal/judge"
	"github.com/markschroedr/watcher-core/internal/runner"
)

type EngineCatalog struct {
	Version   string       `json:"version"`
	Commands  []Definition `json:"commands"`
	Operators []Definition `json:"operators"`
}
type MutationResult struct {
	OK bool `json:"ok"`
}
type AckResult struct {
	Acknowledged []string `json:"acknowledged"`
}
type CheckResult struct {
	OK      bool `json:"ok"`
	Watches int  `json:"watches"`
	Enabled int  `json:"enabled"`
}
type ServiceResult struct {
	Status string `json:"status"`
}

func resultSchema(name string) map[string]any {
	var output any
	switch name {
	case "add", "apply", "remove", "enable", "disable", "wake", "daemon":
		output = new(MutationResult)
	case "status":
		output = new(runner.Status)
	case "findings", "watch":
		output = new([]runner.Finding)
	case "alerts":
		output = new([]delivery.Alert)
	case "ack":
		output = new(AckResult)
	case "judge":
		output = new(judge.Result)
	case "presets":
		output = new(map[string]config.Preset)
	case "service":
		output = new(ServiceResult)
	case "check":
		output = new(CheckResult)
	default:
		panic("missing output contract " + name)
	}
	return Schema(output)
}
func FullCatalog() EngineCatalog {
	c := EngineCatalog{Commands: []Definition{}, Operators: []Definition{}}
	for _, d := range definitions() {
		d.InputSchema = Schema(d.New())
		d.ResultSchema = resultSchema(d.Name)
		if d.Operator {
			c.Operators = append(c.Operators, d)
		} else {
			c.Commands = append(c.Commands, d)
		}
	}
	b, _ := json.Marshal(c)
	hash := sha256.Sum256(b)
	c.Version = fmt.Sprintf("0.1.0+%x", hash[:8])
	return c
}

// Render the vocabulary emitted by our command structs. This is pd-memory's renderer, not a schema runtime.
func typeScriptType(s map[string]any) string {
	if variants, ok := s["anyOf"].([]any); ok {
		types := []string{}
		for _, v := range variants {
			types = append(types, typeScriptType(v.(map[string]any)))
		}
		return "(" + strings.Join(types, " | ") + ")"
	}
	if values, ok := s["enum"].([]any); ok {
		literals := []string{}
		for _, v := range values {
			b, _ := json.Marshal(v)
			literals = append(literals, string(b))
		}
		return strings.Join(literals, " | ")
	}
	switch s["type"] {
	case "null":
		return "null"
	case "string":
		return "string"
	case "boolean":
		return "boolean"
	case "number", "integer":
		return "number"
	case "array":
		if item, ok := s["items"].(map[string]any); ok {
			return "Array<" + typeScriptType(item) + ">"
		}
		return "Array<unknown>"
	case "object":
		required := map[string]bool{}
		keys, _ := s["required"].([]any)
		for _, key := range keys {
			required[key.(string)] = true
		}
		properties, _ := s["properties"].(map[string]any)
		names := []string{}
		for key := range properties {
			names = append(names, key)
		}
		sort.Strings(names)
		lines := []string{}
		for _, key := range names {
			optional := "?"
			if required[key] {
				optional = ""
			}
			encoded, _ := json.Marshal(key)
			lines = append(lines, string(encoded)+optional+": "+typeScriptType(properties[key].(map[string]any))+";")
		}
		if additional, ok := s["additionalProperties"].(map[string]any); ok {
			lines = append(lines, "[key: string]: "+typeScriptType(additional)+";")
		} else if s["additionalProperties"] != false {
			lines = append(lines, "[key: string]: unknown;")
		}
		return "{\n" + strings.Join(lines, "\n") + "\n}"
	}
	return "unknown"
}
func TypeScript(c EngineCatalog) string {
	var out strings.Builder
	fmt.Fprintln(&out, "// Generated by watcher catalog --typescript. Do not edit.")
	fmt.Fprintf(&out, "export const ENGINE_VERSION = %q as const;\n", c.Version)
	all := append(append([]Definition{}, c.Commands...), c.Operators...)
	names := map[string]string{}
	for _, d := range all {
		parts := strings.FieldsFunc(d.Name, func(r rune) bool { return r == '-' || r == ' ' })
		for i, p := range parts {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
		name := strings.Join(parts, "")
		names[d.Name] = name
		fmt.Fprintf(&out, "\nexport type %sInput = %s;\nexport type %sResult = %s;\n", name, typeScriptType(d.InputSchema), name, typeScriptType(d.ResultSchema))
	}
	fmt.Fprintf(&out, "\nexport type CatalogResult = %s;\n", typeScriptType(Schema(new(EngineCatalog))))
	fmt.Fprintln(&out, "\nexport interface Commands {")
	for _, d := range all {
		fmt.Fprintf(&out, "%q: { input: %sInput; result: %sResult };\n", d.Name, names[d.Name], names[d.Name])
	}
	fmt.Fprintln(&out, "\"catalog\": { input: Record<string, never>; result: CatalogResult };\n}\nexport type Command = keyof Commands;")
	return out.String()
}
